// Claim manifest — the per-season { address -> amount, proof } table the claim
// UI reads. Generated by scripts/season-build.ts at season close and hosted as a
// static JSON (default: same-origin /seasons/season-N.json; override the base
// with NEXT_PUBLIC_CLAIM_BASE_URL to point at R2 or a CDN).
//
// TRUST MODEL: the manifest is untrusted. The claim hook re-derives each leaf and
// verifies the proof against the ON-CHAIN root before showing anything, and the
// contract verifies it again on claim(). A stale, truncated, or tampered manifest
// can therefore only ever cause an entry to be skipped — never a wrong payout.
import type { Address, Hex } from "viem";

export interface ClaimEntry {
  /** Raw 18dp wei, as a decimal string (JSON has no bigint). */
  amount: string;
  proof: Hex[];
}

export interface ClaimManifest {
  seasonId: number;
  root: Hex;
  /** Raw 18dp wei, decimal string. */
  pool: string;
  token: Address;
  /** Unix seconds; 0/absent if not pinned at build time. */
  claimDeadline?: number;
  /** Block the leaves were computed at (provenance for reproduction). */
  generatedAtBlock?: string;
  /** Key = lowercased address. */
  claims: Record<string, ClaimEntry>;
}

const BASE = (process.env.NEXT_PUBLIC_CLAIM_BASE_URL ?? "/seasons").replace(/\/$/, "");

// A published manifest is immutable — its root is pinned on-chain at season
// close — so re-fetching it on every 30s claims poll bought nothing. Memoize
// per session: a hit is kept forever, a miss (season not closed / not published
// yet) is retried on a 5-minute TTL so a late publish still appears without a
// reload. Transient fetch failures are NOT memoized — the next poll retries.
const manifestMemo = new Map<number, { at: number; manifest: ClaimManifest | null }>();
const MANIFEST_MISS_TTL_MS = 5 * 60_000;

/** Fetch a season's claim manifest, or null if it isn't published yet (404) or
 *  the fetch fails. Never throws — a missing manifest just means "no claim to
 *  show for this season", which is the normal state before a season closes. */
export async function loadClaimManifest(seasonId: number): Promise<ClaimManifest | null> {
  const hit = manifestMemo.get(seasonId);
  if (hit && (hit.manifest !== null || Date.now() - hit.at < MANIFEST_MISS_TTL_MS)) {
    return hit.manifest;
  }
  try {
    const res = await fetch(`${BASE}/season-${seasonId}.json`, { cache: "no-store" });
    const manifest = res.ok ? ((await res.json()) as ClaimManifest) : null;
    manifestMemo.set(seasonId, { at: Date.now(), manifest });
    return manifest;
  } catch {
    return null;
  }
}
