// GENERATED by scripts/gen-universe.mjs (2026-07-19) — hand-curated, kept in git.
// Source: Jupiter token search; validated tradability via OKX DEX quotes at runtime.
export type XAsset = {
  symbol: string;
  name: string;
  underlying: string;
  mint: string;
  kind: "stock" | "etf";
};

export const USDC_SOL_MINT = "EPjFWdd5AufqSSqeM2qN1xzybapC8G4wEGGkZwyTDt1v";

export const UNIVERSE: XAsset[] = [
  {
    "symbol": "AAPLx",
    "name": "Apple",
    "underlying": "AAPL",
    "mint": "XsbEhLAtcf6HdfpFZ5xEMdqW8nfAvcsP5bdudRLJzJp",
    "kind": "stock"
  },
  {
    "symbol": "ABTx",
    "name": "Abbott",
    "underlying": "ABT",
    "mint": "XsHtf5RpxsQ7jeJ9ivNewouZKJHbPxhPoEy6yYvULr7",
    "kind": "stock"
  },
  {
    "symbol": "AMDx",
    "name": "AMD",
    "underlying": "AMD",
    "mint": "XsXcJ6GZ9kVnjqGsjBnktRcuwMBmvKWh8S93RefZ1rF",
    "kind": "stock"
  },
  {
    "symbol": "AMZNx",
    "name": "Amazon",
    "underlying": "AMZN",
    "mint": "Xs3eBt7uRfJX8QUs4suhyU8p2M6DoUDrJyWBa8LLZsg",
    "kind": "stock"
  },
  {
    "symbol": "ASMLx",
    "name": "ASML",
    "underlying": "ASML",
    "mint": "XshuHQ6o6SVpUNawvnnTMxsZ4tacZsNgVCLorv7TkFq",
    "kind": "stock"
  },
  {
    "symbol": "AVGOx",
    "name": "Broadcom",
    "underlying": "AVGO",
    "mint": "XsgSaSvNSqLTtFuyWPBhK9196Xb9Bbdyjj4fH3cPJGo",
    "kind": "stock"
  },
  {
    "symbol": "AZNx",
    "name": "AstraZeneca",
    "underlying": "AZN",
    "mint": "Xs3ZFkPYT2BN7qBMqf1j1bfTeTm1rFzEFSsQ1z3wAKU",
    "kind": "stock"
  },
  {
    "symbol": "COINx",
    "name": "Coinbase",
    "underlying": "COIN",
    "mint": "Xs7ZdzSHLU9ftNJsii5fCeJhoRWSC32SQGzGQtePxNu",
    "kind": "stock"
  },
  {
    "symbol": "CRCLx",
    "name": "Circle",
    "underlying": "CRCL",
    "mint": "XsueG8BtpquVJX9LVLLEGuViXUungE6WmK5YZ3p3bd1",
    "kind": "stock"
  },
  {
    "symbol": "CRMx",
    "name": "Salesforce",
    "underlying": "CRM",
    "mint": "XsczbcQ3zfcgAEt9qHQES8pxKAVG5rujPSHQEXi4kaN",
    "kind": "stock"
  },
  {
    "symbol": "CSCOx",
    "name": "Cisco",
    "underlying": "CSCO",
    "mint": "Xsr3pdLQyXvDJBFgpR5nexCEZwXvigb8wbPYp4YoNFf",
    "kind": "stock"
  },
  {
    "symbol": "GLDx",
    "name": "Gold",
    "underlying": "GLD",
    "mint": "Xsv9hRk1z5ystj9MhnA7Lq4vjSsLwzL2nxrwmwtD3re",
    "kind": "etf"
  },
  {
    "symbol": "GOOGLx",
    "name": "Alphabet",
    "underlying": "GOOGL",
    "mint": "XsCPL9dNWBMvFtTmwcCA5v3xWPSMEBCszbQdiLLq6aN",
    "kind": "stock"
  },
  {
    "symbol": "HOODx",
    "name": "Robinhood",
    "underlying": "HOOD",
    "mint": "XsvNBAYkrDRNhA7wPHQfX3ZUXZyZLdnCQDfHZ56bzpg",
    "kind": "stock"
  },
  {
    "symbol": "INTCx",
    "name": "Intel",
    "underlying": "INTC",
    "mint": "XshPgPdXFRWB8tP1j82rebb2Q9rPgGX37RuqzohmArM",
    "kind": "stock"
  },
  {
    "symbol": "JNJx",
    "name": "Johnson & Johnson",
    "underlying": "JNJ",
    "mint": "XsGVi5eo1Dh2zUpic4qACcjuWGjNv8GCt3dm5XcX6Dn",
    "kind": "stock"
  },
  {
    "symbol": "JPMx",
    "name": "JPMorgan Chase",
    "underlying": "JPM",
    "mint": "XsMAqkcKsUewDrzVkait4e5u4y8REgtyS7jWgCpLV2C",
    "kind": "stock"
  },
  {
    "symbol": "KOx",
    "name": "Coca-Cola",
    "underlying": "KO",
    "mint": "XsaBXg8dU5cPM6ehmVctMkVqoiRG2ZjMo1cyBJ3AykQ",
    "kind": "stock"
  },
  {
    "symbol": "LLYx",
    "name": "Eli Lilly",
    "underlying": "LLY",
    "mint": "Xsnuv4omNoHozR6EEW5mXkw8Nrny5rB3jVfLqi6gKMH",
    "kind": "stock"
  },
  {
    "symbol": "MCDx",
    "name": "McDonald's",
    "underlying": "MCD",
    "mint": "XsqE9cRRpzxcGKDXj1BJ7Xmg4GRhZoyY1KpmGSxAWT2",
    "kind": "stock"
  },
  {
    "symbol": "METAx",
    "name": "Meta",
    "underlying": "META",
    "mint": "Xsa62P5mvPszXL1krVUnU5ar38bBSVcWAB6fmPCo5Zu",
    "kind": "stock"
  },
  {
    "symbol": "MRKx",
    "name": "Merck",
    "underlying": "MRK",
    "mint": "XsnQnU7AdbRZYe2akqqpibDdXjkieGFfSkbkjX1Sd1X",
    "kind": "stock"
  },
  {
    "symbol": "MSFTx",
    "name": "Microsoft",
    "underlying": "MSFT",
    "mint": "XspzcW1PRtgf6Wj92HCiZdjzKCyFekVD8P5Ueh3dRMX",
    "kind": "stock"
  },
  {
    "symbol": "MSTRx",
    "name": "MicroStrategy",
    "underlying": "MSTR",
    "mint": "XsP7xzNPvEHS1m6qfanPUGjNmdnmsLKEoNAnHjdxxyZ",
    "kind": "stock"
  },
  {
    "symbol": "NFLXx",
    "name": "Netflix",
    "underlying": "NFLX",
    "mint": "XsEH7wWfJJu2ZT3UCFeVfALnVA6CP5ur7Ee11KmzVpL",
    "kind": "stock"
  },
  {
    "symbol": "NVDAx",
    "name": "NVIDIA",
    "underlying": "NVDA",
    "mint": "Xsc9qvGR1efVDFGLrVsmkzv3qi45LTBjeUKSPmx9qEh",
    "kind": "stock"
  },
  {
    "symbol": "NVOx",
    "name": "Novo Nordisk",
    "underlying": "NVO",
    "mint": "XsfAzPzYrYjd4Dpa9BU3cusBsvWfVB9gBcyGC87S57n",
    "kind": "stock"
  },
  {
    "symbol": "ORCLx",
    "name": "Oracle",
    "underlying": "ORCL",
    "mint": "XsjFwUPiLofddX5cWFHW35GCbXcSu1BCUGfxoQAQjeL",
    "kind": "stock"
  },
  {
    "symbol": "PEPx",
    "name": "PepsiCo",
    "underlying": "PEP",
    "mint": "Xsv99frTRUeornyvCfvhnDesQDWuvns1M852Pez91vF",
    "kind": "stock"
  },
  {
    "symbol": "PFEx",
    "name": "Pfizer",
    "underlying": "PFE",
    "mint": "XsAtbqkAP1HJxy7hFDeq7ok6yM43DQ9mQ1Rh861X8rw",
    "kind": "stock"
  },
  {
    "symbol": "PGx",
    "name": "Procter & Gamble",
    "underlying": "PG",
    "mint": "XsYdjDjNUygZ7yGKfQaB6TxLh2gC6RRjzLtLAGJrhzV",
    "kind": "stock"
  },
  {
    "symbol": "PLTRx",
    "name": "Palantir",
    "underlying": "PLTR",
    "mint": "XsoBhf2ufR8fTyNSjqfU71DYGaE6Z3SUGAidpzriAA4",
    "kind": "stock"
  },
  {
    "symbol": "QQQx",
    "name": "Nasdaq",
    "underlying": "QQQ",
    "mint": "Xs8S1uUs1zvS2p7iwtsG3b6fkhpvmwz4GYU3gWAmWHZ",
    "kind": "etf"
  },
  {
    "symbol": "SPCXx",
    "name": "SpaceX",
    "underlying": "SPCX",
    "mint": "Xs3oZwbHvqis4NYcf4YKWmEia2eC84wSiVrcYcTqpH8",
    "kind": "stock"
  },
  {
    "symbol": "SPYx",
    "name": "SP500",
    "underlying": "SPY",
    "mint": "XsoCS1TfEyfFhfvj8EtZ528L3CaKBDBRqRapnBbDF2W",
    "kind": "etf"
  },
  {
    "symbol": "STRCx",
    "name": "Strategy PP Variable",
    "underlying": "STRC",
    "mint": "Xs78JED6PFZxWc2wCEPspZW9kL3Se5J7L5TChKgsidH",
    "kind": "stock"
  },
  {
    "symbol": "TSLAx",
    "name": "Tesla",
    "underlying": "TSLA",
    "mint": "XsDoVfqeBukxuZHWhdvWHBhgEHjGNst4MLodqsJHzoB",
    "kind": "stock"
  },
  {
    "symbol": "TSMx",
    "name": "TSMC",
    "underlying": "TSM",
    "mint": "XsafvsGtzFqqHgTnA3aPC83EAMkacU5mcGtcSayhpVV",
    "kind": "stock"
  },
  {
    "symbol": "UNHx",
    "name": "UnitedHealth",
    "underlying": "UNH",
    "mint": "XszvaiXGPwvk2nwb3o9C1CX4K6zH8sez11E6uyup6fe",
    "kind": "stock"
  },
  {
    "symbol": "Vx",
    "name": "Visa",
    "underlying": "V",
    "mint": "XsqgsbXwWogGJsNcVZ3TyVouy2MbTkfCFhCGGGcQZ2p",
    "kind": "stock"
  },
  {
    "symbol": "WMTx",
    "name": "Walmart",
    "underlying": "WMT",
    "mint": "Xs151QeqTCiuKtinzfRATnUESM2xTU6V9Wy8Vy538ci",
    "kind": "stock"
  },
  {
    "symbol": "XOMx",
    "name": "Exxon Mobil",
    "underlying": "XOM",
    "mint": "XsaHND8sHyfMfsWPj6kSdd5VwvCayZvjYgKmmcNL5qh",
    "kind": "stock"
  }
];

export function assetBySymbol(symbol: string): XAsset | undefined {
  const s = symbol.toLowerCase();
  return UNIVERSE.find((a) => a.symbol.toLowerCase() === s || a.underlying.toLowerCase() === s);
}
